### ISSUE TITLE
3.12.0 Plan 

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/azure-tools-for-java#1937]
### Legend of annotations:

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

#### Web App:
- [x] Support to show **deployment slots** for Web App #1940
- [x] Deploy to **Web App on Linux** #1941
- [ ] ✋View logs for Web App #1942

#### Bug to fix:
- [ ] 🔵 App service without write privilege might block showing other app services. (https://github.com/Microsoft/azure-tools-for-java/issues/1875)

#### Others:
- [x] Investigate NVDA issues. [#1627](https://github.com/Microsoft/azure-tools-for-java/issues/1627) . (Latest status: NVDA 2018.1~2018.3 don't work with IntelliJ IDEA on our machines.)
