### ISSUE TITLE
Iteration Plan for 3.13.0

### ISSUE THREAD

**Issue by SummerSun** [Microsoft/azure-tools-for-java#2050]
### Legend of annotations:

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

### Web Apps
- [x] #2046 Support operations on deployment slot
- [x] #2082 Support to deploy to deployment slots
- [x] #2103 Upgrade Azure SDK to v1.16.0

### Fix bug
- [x] #2021 The deployment slot name is incompleted in UI
