### ISSUE TITLE
Iteration Plan for 3.14.0

### ISSUE THREAD

**Issue by SummerSun** [Microsoft/azure-tools-for-java#2214]
### Legend of annotations:

Mark | Description
-- | --
🏃 | work in progress
✋ | blocked task
💪 | stretch goal for this iteration
🔴 | missing issue reference
🔵 | more investigation required to remove uncertainty
⚫️ | under discussion within the team

### Web Apps
- [x] Deployment slot legacy features
  - [x] #2211 Add operation to delete a deployment slot to Deployment slot legacy features
  - [x] #2212 Support to show properties of a deployment slot
  - [x] #2213 Update the deployment slot area to be hideable
- [x] #2219 Replace OpenJDK with Azul in Dockerfile of Web App for Containers

### Bug fixing
- [x] #2215 The prompt warning message on deleting web app is not correct
- [x] #2310 Discard app settings too slow issue
