### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by andxu** [microsoft/azure-tools-for-java#4780]
* December
    - [x] [service integration]Azure MySQL management
    - [x] [error handling] Actionable Notification
* January
    - [ ] [service integration] Azure Active Directory integration
    - [x] [track2] New common lib for maven and Intellij 
* Back log
    - [ ] [diagnostic] Use own proxy for ssh to web app
    - [ ] [diagnostic] Open jfr in intellij

**Comment by andxu** [comment]
Out dated
